#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'RadioCountMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 10

# The Active Message type associated with this message.
AM_TYPE = 6

class RadioCountMsg(tinyos.message.Message.Message):
    # Create a new RadioCountMsg of size 10.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=10):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <RadioCountMsg> \n"
        try:
            s += "  [counter=0x%x]\n" % (self.get_counter())
        except:
            pass
        try:
            s += "  [tx_tmsp=0x%x]\n" % (self.get_tx_tmsp())
        except:
            pass
        try:
            s += "  [rx_tmsp=0x%x]\n" % (self.get_rx_tmsp())
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: counter
    #   Field type: int
    #   Offset (bits): 0
    #   Size (bits): 16
    #

    #
    # Return whether the field 'counter' is signed (False).
    #
    def isSigned_counter(self):
        return False
    
    #
    # Return whether the field 'counter' is an array (False).
    #
    def isArray_counter(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'counter'
    #
    def offset_counter(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'counter'
    #
    def offsetBits_counter(self):
        return 0
    
    #
    # Return the value (as a int) of the field 'counter'
    #
    def get_counter(self):
        return self.getUIntElement(self.offsetBits_counter(), 16, 1)
    
    #
    # Set the value of the field 'counter'
    #
    def set_counter(self, value):
        self.setUIntElement(self.offsetBits_counter(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'counter'
    #
    def size_counter(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'counter'
    #
    def sizeBits_counter(self):
        return 16
    
    #
    # Accessor methods for field: tx_tmsp
    #   Field type: long
    #   Offset (bits): 16
    #   Size (bits): 32
    #

    #
    # Return whether the field 'tx_tmsp' is signed (False).
    #
    def isSigned_tx_tmsp(self):
        return False
    
    #
    # Return whether the field 'tx_tmsp' is an array (False).
    #
    def isArray_tx_tmsp(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'tx_tmsp'
    #
    def offset_tx_tmsp(self):
        return (16 / 8)
    
    #
    # Return the offset (in bits) of the field 'tx_tmsp'
    #
    def offsetBits_tx_tmsp(self):
        return 16
    
    #
    # Return the value (as a long) of the field 'tx_tmsp'
    #
    def get_tx_tmsp(self):
        return self.getUIntElement(self.offsetBits_tx_tmsp(), 32, 1)
    
    #
    # Set the value of the field 'tx_tmsp'
    #
    def set_tx_tmsp(self, value):
        self.setUIntElement(self.offsetBits_tx_tmsp(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'tx_tmsp'
    #
    def size_tx_tmsp(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'tx_tmsp'
    #
    def sizeBits_tx_tmsp(self):
        return 32
    
    #
    # Accessor methods for field: rx_tmsp
    #   Field type: long
    #   Offset (bits): 48
    #   Size (bits): 32
    #

    #
    # Return whether the field 'rx_tmsp' is signed (False).
    #
    def isSigned_rx_tmsp(self):
        return False
    
    #
    # Return whether the field 'rx_tmsp' is an array (False).
    #
    def isArray_rx_tmsp(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'rx_tmsp'
    #
    def offset_rx_tmsp(self):
        return (48 / 8)
    
    #
    # Return the offset (in bits) of the field 'rx_tmsp'
    #
    def offsetBits_rx_tmsp(self):
        return 48
    
    #
    # Return the value (as a long) of the field 'rx_tmsp'
    #
    def get_rx_tmsp(self):
        return self.getUIntElement(self.offsetBits_rx_tmsp(), 32, 1)
    
    #
    # Set the value of the field 'rx_tmsp'
    #
    def set_rx_tmsp(self, value):
        self.setUIntElement(self.offsetBits_rx_tmsp(), 32, value, 1)
    
    #
    # Return the size, in bytes, of the field 'rx_tmsp'
    #
    def size_rx_tmsp(self):
        return (32 / 8)
    
    #
    # Return the size, in bits, of the field 'rx_tmsp'
    #
    def sizeBits_rx_tmsp(self):
        return 32
    
